# Generated by Django 5.0.1 on 2024-01-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
