# Generated by Django 5.0.1 on 2024-01-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='price',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
